spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/price_comparator
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  address: 0.0.0.0
  port: 8080

logging:
  level:
    eu.accesa.price_comparator: INFO
